//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Functions
    {
        public int FunctionID { get; set; }
        public string FunctionName { get; set; }
        public int Superior { get; set; }
        public bool MasterMenu { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsDel { get; set; }
        public Nullable<bool> IsPhone { get; set; }
    }
}
