//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jokul_Forum_GradeLog
    {
        public int Id { get; set; }
        public int BoardId { get; set; }
        public int TopicId { get; set; }
        public int PostId { get; set; }
        public int UserId { get; set; }
        public string Username { get; set; }
        public decimal Credit1 { get; set; }
        public decimal Credit2 { get; set; }
        public decimal Credit3 { get; set; }
        public decimal Credit4 { get; set; }
        public decimal Credit5 { get; set; }
        public decimal Credit6 { get; set; }
        public decimal Credit7 { get; set; }
        public decimal Credit8 { get; set; }
        public decimal Credit9 { get; set; }
        public decimal Credit10 { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Reason { get; set; }
    }
}
