//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jokul_Forum_GroupExtended
    {
        public int GroupId { get; set; }
        public int ViewIpField { get; set; }
        public string AttachmentExtension { get; set; }
        public int DayAttachmentSize { get; set; }
        public int PostIntervalSecond { get; set; }
        public byte Search { get; set; }
        public byte MemberList { get; set; }
        public byte PostCheck { get; set; }
        public bool Cost { get; set; }
        public decimal CostMax { get; set; }
        public int PostUpdateLog { get; set; }
    }
}
