//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jokul_Passport_ShortMessage
    {
        public long Id { get; set; }
        public int UserId { get; set; }
        public int Floder { get; set; }
        public int SenderId { get; set; }
        public string SenderUsername { get; set; }
        public int ReceiverId { get; set; }
        public string ReceiverUsername { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public System.DateTime DateTime { get; set; }
        public byte New { get; set; }
        public byte Format { get; set; }
    }
}
