//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jokul_Forum_Post_1
    {
        public int Id { get; set; }
        public int BoardId { get; set; }
        public int TopicId { get; set; }
        public int PostUserId { get; set; }
        public string PostUsername { get; set; }
        public string PostUserIp { get; set; }
        public System.DateTime PostDateTime { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public byte HTML { get; set; }
        public byte Smile { get; set; }
        public byte UBB { get; set; }
        public int Attachment { get; set; }
        public byte Signature { get; set; }
        public byte Url { get; set; }
        public byte Audit { get; set; }
        public byte First { get; set; }
        public byte Invisible { get; set; }
        public byte Ban { get; set; }
        public int Grade { get; set; }
        public byte Hide { get; set; }
        public int UpdateUserId { get; set; }
        public string UpdateUsername { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
