//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jokul_Forum_TaskQueue
    {
        public int Id { get; set; }
        public int instance { get; set; }
        public string instance_token { get; set; }
        public string token { get; set; }
        public System.DateTime create_time { get; set; }
        public string type { get; set; }
        public string data { get; set; }
        public string shape { get; set; }
    }
}
