//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jokul_Forum_BoardActionPoint
    {
        public int Id { get; set; }
        public int Enable { get; set; }
        public int BoardId { get; set; }
        public int GroupId { get; set; }
        public int ActionId { get; set; }
        public decimal Point_1 { get; set; }
        public decimal Point_2 { get; set; }
        public decimal Point_3 { get; set; }
        public decimal Point_4 { get; set; }
        public decimal Point_5 { get; set; }
        public decimal Point_6 { get; set; }
        public decimal Point_7 { get; set; }
        public decimal Point_8 { get; set; }
        public decimal Point_9 { get; set; }
        public decimal Point_10 { get; set; }
    }
}
