//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jokul_Forum_BoardManagePermission
    {
        public int Id { get; set; }
        public int BoardId { get; set; }
        public int GroupId { get; set; }
        public int UpdateTopic { get; set; }
        public int UpdateReply { get; set; }
        public int DeleteTopic { get; set; }
        public int DeleteReply { get; set; }
        public int TopTopic_1 { get; set; }
        public int TopTopic_2 { get; set; }
        public int TopTopic_3 { get; set; }
        public int AuditTopic { get; set; }
        public int AuditReply { get; set; }
        public int DigestTopic { get; set; }
        public int BanTopic { get; set; }
        public int BanReply { get; set; }
        public int HighLightTopic { get; set; }
        public int CloseTopic { get; set; }
        public int MoveTopic { get; set; }
        public int DestructionRatePost { get; set; }
    }
}
