//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jokul_Forum_Group
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public byte System { get; set; }
        public byte Type { get; set; }
        public int CreditLower { get; set; }
        public int CreditHigher { get; set; }
        public int Order { get; set; }
        public string Color { get; set; }
        public string Image { get; set; }
        public string OnlineImage { get; set; }
    }
}
