//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jokul_Forum_Attachment
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int BoardId { get; set; }
        public int TopicId { get; set; }
        public int PostId { get; set; }
        public System.DateTime UploadDatetime { get; set; }
        public string Name { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public string FileType { get; set; }
        public int FileSize { get; set; }
        public byte IsImage { get; set; }
        public byte Thumb { get; set; }
        public int Download { get; set; }
        public decimal Cost { get; set; }
        public byte CostType { get; set; }
    }
}
