//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jokul_Forum_Statistic
    {
        public int Id { get; set; }
        public int LastUserId { get; set; }
        public string LastUserNickname { get; set; }
        public int Topic { get; set; }
        public int Post { get; set; }
        public int User { get; set; }
        public int HighestOnline { get; set; }
        public System.DateTime HighestOnlineDateTime { get; set; }
        public int TodayTopic { get; set; }
        public int TodayPost { get; set; }
        public int TodayUser { get; set; }
        public int YesterdayTopic { get; set; }
        public int YesterdayPost { get; set; }
        public int YesterdayUser { get; set; }
    }
}
