//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jokul_Forum_Board
    {
        public int Id { get; set; }
        public int ParentId { get; set; }
        public int LeftNumber { get; set; }
        public int RightNumber { get; set; }
        public int Layer { get; set; }
        public int ChildCount { get; set; }
        public string Name { get; set; }
        public int TodayTopicCount { get; set; }
        public int TopicCount { get; set; }
        public int PostCount { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string Icon { get; set; }
        public string Rule { get; set; }
        public string Description { get; set; }
        public short ChildCol { get; set; }
        public int LastPostUserId { get; set; }
        public string LastPostUsername { get; set; }
        public int LastTopicId { get; set; }
        public string LastTopicTitle { get; set; }
        public string Url { get; set; }
        public int Show { get; set; }
    }
}
