//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jokul_Passport_User
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int GroupId { get; set; }
        public string CreateIp { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string LastIp { get; set; }
        public System.DateTime LastDatetime { get; set; }
        public int PMCount { get; set; }
        public int PMNewCount { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public string Email { get; set; }
        public string UnevaluatedEmail { get; set; }
        public int Avatar { get; set; }
    }
}
