//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jokul_Forum_BoardExtended
    {
        public int BoardId { get; set; }
        public int ShowTopic { get; set; }
        public int ShowTopicBoard { get; set; }
        public string AttachTitle { get; set; }
        public int TopicType { get; set; }
        public int SkinId { get; set; }
        public bool Jammer { get; set; }
        public bool QuicklyReply { get; set; }
        public bool Recycle { get; set; }
        public int DefaultOrderField { get; set; }
        public int DefaultOrder { get; set; }
        public bool PicStyle { get; set; }
        public string SEOKeywords { get; set; }
        public string SEODescription { get; set; }
        public string Domain { get; set; }
    }
}
