//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jokul_Forum_ManageLog
    {
        public int Id { get; set; }
        public string Ip { get; set; }
        public int UserId { get; set; }
        public string Username { get; set; }
        public byte Action { get; set; }
        public string Description { get; set; }
        public System.DateTime DateTime { get; set; }
        public int BoardId { get; set; }
        public string BoardName { get; set; }
        public int TopicId { get; set; }
        public string TopicTitle { get; set; }
        public int PostId { get; set; }
    }
}
