//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jokul_Forum_BoardPermission
    {
        public int Id { get; set; }
        public int BoardId { get; set; }
        public int GroupId { get; set; }
        public int VisitBoard { get; set; }
        public int VisitTopic { get; set; }
        public int PostTopic { get; set; }
        public int PostReply { get; set; }
        public int UploadAttachment { get; set; }
        public int ViewAttachment { get; set; }
        public int UpdateMyselfTopic { get; set; }
        public int UpdateMyselfReply { get; set; }
        public int DeleteMyselfTopic { get; set; }
        public int DeleteMyselfReply { get; set; }
        public int PostBanTopic { get; set; }
        public int ViewBanTopic { get; set; }
        public int RateTopic { get; set; }
        public int RateReply { get; set; }
    }
}
