//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MinHangBBSDataEntities1 : DbContext
    {
        public MinHangBBSDataEntities1()
            : base("name=MinHangBBSDataEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Jokul_Forum_Advertisement> Jokul_Forum_Advertisement { get; set; }
        public DbSet<Jokul_Forum_Announcement> Jokul_Forum_Announcement { get; set; }
        public DbSet<Jokul_Forum_Application> Jokul_Forum_Application { get; set; }
        public DbSet<Jokul_Forum_Attachment> Jokul_Forum_Attachment { get; set; }
        public DbSet<Jokul_Forum_AttachmentBuy> Jokul_Forum_AttachmentBuy { get; set; }
        public DbSet<Jokul_Forum_Board> Jokul_Forum_Board { get; set; }
        public DbSet<Jokul_Forum_BoardActionPoint> Jokul_Forum_BoardActionPoint { get; set; }
        public DbSet<Jokul_Forum_BoardExtended> Jokul_Forum_BoardExtended { get; set; }
        public DbSet<Jokul_Forum_BoardManagePermission> Jokul_Forum_BoardManagePermission { get; set; }
        public DbSet<Jokul_Forum_BoardPermission> Jokul_Forum_BoardPermission { get; set; }
        public DbSet<Jokul_Forum_BoardRate> Jokul_Forum_BoardRate { get; set; }
        public DbSet<Jokul_Forum_BoardTopicType> Jokul_Forum_BoardTopicType { get; set; }
        public DbSet<Jokul_Forum_Buddy> Jokul_Forum_Buddy { get; set; }
        public DbSet<Jokul_Forum_EmotionCategory> Jokul_Forum_EmotionCategory { get; set; }
        public DbSet<Jokul_Forum_Favorite> Jokul_Forum_Favorite { get; set; }
        public DbSet<Jokul_Forum_GradeLog> Jokul_Forum_GradeLog { get; set; }
        public DbSet<Jokul_Forum_Group> Jokul_Forum_Group { get; set; }
        public DbSet<Jokul_Forum_GroupExtended> Jokul_Forum_GroupExtended { get; set; }
        public DbSet<Jokul_Forum_GroupManagePermission> Jokul_Forum_GroupManagePermission { get; set; }
        public DbSet<Jokul_Forum_Help> Jokul_Forum_Help { get; set; }
        public DbSet<Jokul_Forum_Link> Jokul_Forum_Link { get; set; }
        public DbSet<Jokul_Forum_Log> Jokul_Forum_Log { get; set; }
        public DbSet<Jokul_Forum_ManageLog> Jokul_Forum_ManageLog { get; set; }
        public DbSet<Jokul_Forum_Medal> Jokul_Forum_Medal { get; set; }
        public DbSet<Jokul_Forum_Moderator> Jokul_Forum_Moderator { get; set; }
        public DbSet<Jokul_Forum_MyPost> Jokul_Forum_MyPost { get; set; }
        public DbSet<Jokul_Forum_MyTopic> Jokul_Forum_MyTopic { get; set; }
        public DbSet<Jokul_Forum_Nav> Jokul_Forum_Nav { get; set; }
        public DbSet<Jokul_Forum_Online> Jokul_Forum_Online { get; set; }
        public DbSet<Jokul_Forum_Plugin> Jokul_Forum_Plugin { get; set; }
        public DbSet<Jokul_Forum_Post_1> Jokul_Forum_Post_1 { get; set; }
        public DbSet<Jokul_Forum_PostId> Jokul_Forum_PostId { get; set; }
        public DbSet<Jokul_Forum_PostSubTable> Jokul_Forum_PostSubTable { get; set; }
        public DbSet<Jokul_Forum_RatePost> Jokul_Forum_RatePost { get; set; }
        public DbSet<Jokul_Forum_RateSnapshot> Jokul_Forum_RateSnapshot { get; set; }
        public DbSet<Jokul_Forum_RateUser> Jokul_Forum_RateUser { get; set; }
        public DbSet<Jokul_Forum_SearchCache> Jokul_Forum_SearchCache { get; set; }
        public DbSet<Jokul_Forum_Settings> Jokul_Forum_Settings { get; set; }
        public DbSet<Jokul_Forum_Skin> Jokul_Forum_Skin { get; set; }
        public DbSet<Jokul_Forum_Smile> Jokul_Forum_Smile { get; set; }
        public DbSet<Jokul_Forum_StatDay> Jokul_Forum_StatDay { get; set; }
        public DbSet<Jokul_Forum_Statistic> Jokul_Forum_Statistic { get; set; }
        public DbSet<Jokul_Forum_SystemLog> Jokul_Forum_SystemLog { get; set; }
        public DbSet<Jokul_Forum_Tag> Jokul_Forum_Tag { get; set; }
        public DbSet<Jokul_Forum_Task> Jokul_Forum_Task { get; set; }
        public DbSet<Jokul_Forum_TaskQueue> Jokul_Forum_TaskQueue { get; set; }
        public DbSet<Jokul_Forum_TaskQueueService> Jokul_Forum_TaskQueueService { get; set; }
        public DbSet<Jokul_Forum_Topic> Jokul_Forum_Topic { get; set; }
        public DbSet<Jokul_Forum_TopicTag> Jokul_Forum_TopicTag { get; set; }
        public DbSet<Jokul_Forum_User> Jokul_Forum_User { get; set; }
        public DbSet<Jokul_Forum_UserExtended> Jokul_Forum_UserExtended { get; set; }
        public DbSet<Jokul_Forum_Word> Jokul_Forum_Word { get; set; }
        public DbSet<Jokul_Passport_Application> Jokul_Passport_Application { get; set; }
        public DbSet<Jokul_Passport_FailedLogin> Jokul_Passport_FailedLogin { get; set; }
        public DbSet<Jokul_Passport_Friend> Jokul_Passport_Friend { get; set; }
        public DbSet<Jokul_Passport_FriendInvite> Jokul_Passport_FriendInvite { get; set; }
        public DbSet<Jokul_Passport_Group> Jokul_Passport_Group { get; set; }
        public DbSet<Jokul_Passport_Log> Jokul_Passport_Log { get; set; }
        public DbSet<Jokul_Passport_Note> Jokul_Passport_Note { get; set; }
        public DbSet<Jokul_Passport_OAuthPlugin> Jokul_Passport_OAuthPlugin { get; set; }
        public DbSet<Jokul_Passport_OAuthUser> Jokul_Passport_OAuthUser { get; set; }
        public DbSet<Jokul_Passport_Setting> Jokul_Passport_Setting { get; set; }
        public DbSet<Jokul_Passport_ShortMessage> Jokul_Passport_ShortMessage { get; set; }
        public DbSet<Jokul_Passport_Skin> Jokul_Passport_Skin { get; set; }
        public DbSet<Jokul_Passport_SystemLog> Jokul_Passport_SystemLog { get; set; }
        public DbSet<Jokul_Passport_Task> Jokul_Passport_Task { get; set; }
        public DbSet<Jokul_Passport_Unique> Jokul_Passport_Unique { get; set; }
        public DbSet<Jokul_Passport_User> Jokul_Passport_User { get; set; }
        public DbSet<Jokul_Passport_VerifyCode> Jokul_Passport_VerifyCode { get; set; }
    
        public virtual ObjectResult<Nullable<int>> Jokul_Forum_GetDigestCount(Nullable<int> boardId)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Jokul_Forum_GetDigestCount", boardIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Jokul_Forum_GetDigestCount_All(Nullable<int> boardId)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Jokul_Forum_GetDigestCount_All", boardIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Jokul_Forum_GetDigestCount_Ex(Nullable<int> boardId)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Jokul_Forum_GetDigestCount_Ex", boardIdParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetDigestList_All_LastPost_Asc_Result> Jokul_Forum_GetDigestList_All_LastPost_Asc(Nullable<int> start, Nullable<int> lenght)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetDigestList_All_LastPost_Asc_Result>("Jokul_Forum_GetDigestList_All_LastPost_Asc", startParameter, lenghtParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetDigestList_All_LastPost_Desc_Result> Jokul_Forum_GetDigestList_All_LastPost_Desc(Nullable<int> start, Nullable<int> lenght)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetDigestList_All_LastPost_Desc_Result>("Jokul_Forum_GetDigestList_All_LastPost_Desc", startParameter, lenghtParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetDigestList_All_Post_Asc_Result> Jokul_Forum_GetDigestList_All_Post_Asc(Nullable<int> start, Nullable<int> lenght)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetDigestList_All_Post_Asc_Result>("Jokul_Forum_GetDigestList_All_Post_Asc", startParameter, lenghtParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetDigestList_All_Post_Desc_Result> Jokul_Forum_GetDigestList_All_Post_Desc(Nullable<int> start, Nullable<int> lenght)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetDigestList_All_Post_Desc_Result>("Jokul_Forum_GetDigestList_All_Post_Desc", startParameter, lenghtParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetDigestList_Ex_LastPost_Asc_Result> Jokul_Forum_GetDigestList_Ex_LastPost_Asc(Nullable<int> boardId, Nullable<int> start, Nullable<int> lenght)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetDigestList_Ex_LastPost_Asc_Result>("Jokul_Forum_GetDigestList_Ex_LastPost_Asc", boardIdParameter, startParameter, lenghtParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetDigestList_Ex_LastPost_Desc_Result> Jokul_Forum_GetDigestList_Ex_LastPost_Desc(Nullable<int> boardId, Nullable<int> start, Nullable<int> lenght)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetDigestList_Ex_LastPost_Desc_Result>("Jokul_Forum_GetDigestList_Ex_LastPost_Desc", boardIdParameter, startParameter, lenghtParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetDigestList_Ex_Post_asc_Result> Jokul_Forum_GetDigestList_Ex_Post_asc(Nullable<int> boardId, Nullable<int> start, Nullable<int> lenght)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetDigestList_Ex_Post_asc_Result>("Jokul_Forum_GetDigestList_Ex_Post_asc", boardIdParameter, startParameter, lenghtParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetDigestList_Ex_Post_Desc_Result> Jokul_Forum_GetDigestList_Ex_Post_Desc(Nullable<int> boardId, Nullable<int> start, Nullable<int> lenght)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetDigestList_Ex_Post_Desc_Result>("Jokul_Forum_GetDigestList_Ex_Post_Desc", boardIdParameter, startParameter, lenghtParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetDigestList_LastPost_Asc_Result> Jokul_Forum_GetDigestList_LastPost_Asc(Nullable<int> start, Nullable<int> lenght, Nullable<int> boardId)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetDigestList_LastPost_Asc_Result>("Jokul_Forum_GetDigestList_LastPost_Asc", startParameter, lenghtParameter, boardIdParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetDigestList_LastPost_Desc_Result> Jokul_Forum_GetDigestList_LastPost_Desc(Nullable<int> start, Nullable<int> lenght, Nullable<int> boardId)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetDigestList_LastPost_Desc_Result>("Jokul_Forum_GetDigestList_LastPost_Desc", startParameter, lenghtParameter, boardIdParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetDigestList_Post_Asc_Result> Jokul_Forum_GetDigestList_Post_Asc(Nullable<int> start, Nullable<int> lenght, Nullable<int> boardId)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetDigestList_Post_Asc_Result>("Jokul_Forum_GetDigestList_Post_Asc", startParameter, lenghtParameter, boardIdParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetDigestList_Post_Desc_Result> Jokul_Forum_GetDigestList_Post_Desc(Nullable<int> start, Nullable<int> lenght, Nullable<int> boardId)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetDigestList_Post_Desc_Result>("Jokul_Forum_GetDigestList_Post_Desc", startParameter, lenghtParameter, boardIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Jokul_Forum_GetNewCount(Nullable<int> bid, Nullable<System.DateTime> dt)
        {
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Jokul_Forum_GetNewCount", bidParameter, dtParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Jokul_Forum_GetNewCount_All(Nullable<System.DateTime> dt)
        {
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Jokul_Forum_GetNewCount_All", dtParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Jokul_Forum_GetNewCount_Ex(Nullable<int> bid, Nullable<System.DateTime> dt)
        {
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Jokul_Forum_GetNewCount_Ex", bidParameter, dtParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetNewList_Result> Jokul_Forum_GetNewList(Nullable<int> start, Nullable<int> lenght, Nullable<int> bid, Nullable<System.DateTime> dt)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetNewList_Result>("Jokul_Forum_GetNewList", startParameter, lenghtParameter, bidParameter, dtParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetNewList_All_Result> Jokul_Forum_GetNewList_All(Nullable<int> start, Nullable<int> lenght, Nullable<System.DateTime> dt)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetNewList_All_Result>("Jokul_Forum_GetNewList_All", startParameter, lenghtParameter, dtParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetNewList_Ex_Result> Jokul_Forum_GetNewList_Ex(Nullable<int> bid, Nullable<int> start, Nullable<int> lenght, Nullable<System.DateTime> dt)
        {
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetNewList_Ex_Result>("Jokul_Forum_GetNewList_Ex", bidParameter, startParameter, lenghtParameter, dtParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Jokul_Forum_GetTopicCount(Nullable<int> boardId)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Jokul_Forum_GetTopicCount", boardIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Jokul_Forum_GetTopicCount_Ex(Nullable<int> boardId)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Jokul_Forum_GetTopicCount_Ex", boardIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Jokul_Forum_GetTopicCount_TopicType(Nullable<int> boardId, Nullable<int> topicTypeId)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            var topicTypeIdParameter = topicTypeId.HasValue ?
                new ObjectParameter("TopicTypeId", topicTypeId) :
                new ObjectParameter("TopicTypeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Jokul_Forum_GetTopicCount_TopicType", boardIdParameter, topicTypeIdParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetTopicList_Ex_LastPost_Asc_Result> Jokul_Forum_GetTopicList_Ex_LastPost_Asc(Nullable<int> boardId, Nullable<int> start, Nullable<int> lenght)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetTopicList_Ex_LastPost_Asc_Result>("Jokul_Forum_GetTopicList_Ex_LastPost_Asc", boardIdParameter, startParameter, lenghtParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetTopicList_Ex_LastPost_Desc_Result> Jokul_Forum_GetTopicList_Ex_LastPost_Desc(Nullable<int> boardId, Nullable<int> start, Nullable<int> lenght)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetTopicList_Ex_LastPost_Desc_Result>("Jokul_Forum_GetTopicList_Ex_LastPost_Desc", boardIdParameter, startParameter, lenghtParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetTopicList_Ex_Post_Asc_Result> Jokul_Forum_GetTopicList_Ex_Post_Asc(Nullable<int> boardId, Nullable<int> start, Nullable<int> lenght)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetTopicList_Ex_Post_Asc_Result>("Jokul_Forum_GetTopicList_Ex_Post_Asc", boardIdParameter, startParameter, lenghtParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetTopicList_Ex_Post_Desc_Result> Jokul_Forum_GetTopicList_Ex_Post_Desc(Nullable<int> boardId, Nullable<int> start, Nullable<int> lenght)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetTopicList_Ex_Post_Desc_Result>("Jokul_Forum_GetTopicList_Ex_Post_Desc", boardIdParameter, startParameter, lenghtParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetTopicList_LastPost_Asc_Result> Jokul_Forum_GetTopicList_LastPost_Asc(Nullable<int> boardId, Nullable<int> start, Nullable<int> lenght)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetTopicList_LastPost_Asc_Result>("Jokul_Forum_GetTopicList_LastPost_Asc", boardIdParameter, startParameter, lenghtParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetTopicList_LastPost_Desc_Result> Jokul_Forum_GetTopicList_LastPost_Desc(Nullable<int> boardId, Nullable<int> start, Nullable<int> lenght)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetTopicList_LastPost_Desc_Result>("Jokul_Forum_GetTopicList_LastPost_Desc", boardIdParameter, startParameter, lenghtParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetTopicList_Post_Asc_Result> Jokul_Forum_GetTopicList_Post_Asc(Nullable<int> boardId, Nullable<int> start, Nullable<int> lenght)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetTopicList_Post_Asc_Result>("Jokul_Forum_GetTopicList_Post_Asc", boardIdParameter, startParameter, lenghtParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetTopicList_Post_Desc_Result> Jokul_Forum_GetTopicList_Post_Desc(Nullable<int> boardId, Nullable<int> start, Nullable<int> lenght)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetTopicList_Post_Desc_Result>("Jokul_Forum_GetTopicList_Post_Desc", boardIdParameter, startParameter, lenghtParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetTopicList_TopicType_LastPost_Asc_Result> Jokul_Forum_GetTopicList_TopicType_LastPost_Asc(Nullable<int> boardId, Nullable<int> start, Nullable<int> lenght, Nullable<int> topicTypeId)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            var topicTypeIdParameter = topicTypeId.HasValue ?
                new ObjectParameter("topicTypeId", topicTypeId) :
                new ObjectParameter("topicTypeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetTopicList_TopicType_LastPost_Asc_Result>("Jokul_Forum_GetTopicList_TopicType_LastPost_Asc", boardIdParameter, startParameter, lenghtParameter, topicTypeIdParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetTopicList_TopicType_LastPost_Desc_Result> Jokul_Forum_GetTopicList_TopicType_LastPost_Desc(Nullable<int> boardId, Nullable<int> start, Nullable<int> lenght, Nullable<int> topicTypeId)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            var topicTypeIdParameter = topicTypeId.HasValue ?
                new ObjectParameter("topicTypeId", topicTypeId) :
                new ObjectParameter("topicTypeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetTopicList_TopicType_LastPost_Desc_Result>("Jokul_Forum_GetTopicList_TopicType_LastPost_Desc", boardIdParameter, startParameter, lenghtParameter, topicTypeIdParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetTopicList_TopicType_Post_Asc_Result> Jokul_Forum_GetTopicList_TopicType_Post_Asc(Nullable<int> boardId, Nullable<int> start, Nullable<int> lenght, Nullable<int> topicTypeId)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            var topicTypeIdParameter = topicTypeId.HasValue ?
                new ObjectParameter("topicTypeId", topicTypeId) :
                new ObjectParameter("topicTypeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetTopicList_TopicType_Post_Asc_Result>("Jokul_Forum_GetTopicList_TopicType_Post_Asc", boardIdParameter, startParameter, lenghtParameter, topicTypeIdParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetTopicList_TopicType_Post_Desc_Result> Jokul_Forum_GetTopicList_TopicType_Post_Desc(Nullable<int> boardId, Nullable<int> start, Nullable<int> lenght, Nullable<int> topicTypeId)
        {
            var boardIdParameter = boardId.HasValue ?
                new ObjectParameter("BoardId", boardId) :
                new ObjectParameter("BoardId", typeof(int));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            var topicTypeIdParameter = topicTypeId.HasValue ?
                new ObjectParameter("topicTypeId", topicTypeId) :
                new ObjectParameter("topicTypeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetTopicList_TopicType_Post_Desc_Result>("Jokul_Forum_GetTopicList_TopicType_Post_Desc", boardIdParameter, startParameter, lenghtParameter, topicTypeIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Jokul_Forum_GetTopTopicCount(Nullable<int> bId)
        {
            var bIdParameter = bId.HasValue ?
                new ObjectParameter("BId", bId) :
                new ObjectParameter("BId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Jokul_Forum_GetTopTopicCount", bIdParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetTopTopicList_Result> Jokul_Forum_GetTopTopicList(Nullable<int> start, Nullable<int> lenght, Nullable<int> bId)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(int));
    
            var lenghtParameter = lenght.HasValue ?
                new ObjectParameter("lenght", lenght) :
                new ObjectParameter("lenght", typeof(int));
    
            var bIdParameter = bId.HasValue ?
                new ObjectParameter("bId", bId) :
                new ObjectParameter("bId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetTopTopicList_Result>("Jokul_Forum_GetTopTopicList", startParameter, lenghtParameter, bIdParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetTopTopicList_All_Result> Jokul_Forum_GetTopTopicList_All(Nullable<int> bid)
        {
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetTopTopicList_All_Result>("Jokul_Forum_GetTopTopicList_All", bidParameter);
        }
    
        public virtual ObjectResult<Jokul_Forum_GetTopTopicList_Only_Result> Jokul_Forum_GetTopTopicList_Only(Nullable<int> bid)
        {
            var bidParameter = bid.HasValue ?
                new ObjectParameter("bid", bid) :
                new ObjectParameter("bid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Jokul_Forum_GetTopTopicList_Only_Result>("Jokul_Forum_GetTopTopicList_Only", bidParameter);
        }
    
        public virtual int Jokul_SP_DeleteDefault(string tableName, string columnName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            var columnNameParameter = columnName != null ?
                new ObjectParameter("columnName", columnName) :
                new ObjectParameter("columnName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Jokul_SP_DeleteDefault", tableNameParameter, columnNameParameter);
        }
    
        public virtual int Jokul_SP_DropIndex(string tbName)
        {
            var tbNameParameter = tbName != null ?
                new ObjectParameter("tbName", tbName) :
                new ObjectParameter("tbName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Jokul_SP_DropIndex", tbNameParameter);
        }
    
        public virtual int Jokul_SP_TextReplace(string tableStr, string pKField, string fieldStr, string sourceStr, string replaceStr)
        {
            var tableStrParameter = tableStr != null ?
                new ObjectParameter("TableStr", tableStr) :
                new ObjectParameter("TableStr", typeof(string));
    
            var pKFieldParameter = pKField != null ?
                new ObjectParameter("PKField", pKField) :
                new ObjectParameter("PKField", typeof(string));
    
            var fieldStrParameter = fieldStr != null ?
                new ObjectParameter("FieldStr", fieldStr) :
                new ObjectParameter("FieldStr", typeof(string));
    
            var sourceStrParameter = sourceStr != null ?
                new ObjectParameter("SourceStr", sourceStr) :
                new ObjectParameter("SourceStr", typeof(string));
    
            var replaceStrParameter = replaceStr != null ?
                new ObjectParameter("ReplaceStr", replaceStr) :
                new ObjectParameter("ReplaceStr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Jokul_SP_TextReplace", tableStrParameter, pKFieldParameter, fieldStrParameter, sourceStrParameter, replaceStrParameter);
        }
    }
}
