//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbApplyBill
    {
        public int ApplyID { get; set; }
        public string ApplyType { get; set; }
        public string ObjectID { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public string Updater { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> StateType { get; set; }
    
        public virtual tbConfirmState tbConfirmState { get; set; }
    }
}
