//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCar
    {
        public string CarID { get; set; }
        public int Version { get; set; }
        public string CarLicence { get; set; }
        public string CarType { get; set; }
        public string CarVehicleNo { get; set; }
        public Nullable<decimal> MaxWeight { get; set; }
        public Nullable<decimal> MinWeight { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<decimal> StateCode { get; set; }
        public string ResFiles { get; set; }
        public string Drivers { get; set; }
        public string CurrProject { get; set; }
        public string ParkSpace { get; set; }
        public string JobPartTime { get; set; }
        public string SkillItem { get; set; }
        public Nullable<int> CarPic { get; set; }
    }
}
