//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOwnerRfid
    {
        public int RfidAutoId { get; set; }
        public int UseType { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string ObjectID { get; set; }
        public Nullable<int> ListType { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual mtOwner mtOwner { get; set; }
        public virtual mtRfidCode mtRfidCode { get; set; }
    }
}
