//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPeople
    {
        public string PeopleID { get; set; }
        public int Version { get; set; }
        public string PeopleName { get; set; }
        public string Sexy { get; set; }
        public string Position { get; set; }
        public string PhoneNum { get; set; }
        public string IdentityCardID { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> StateCode { get; set; }
        public Nullable<int> Age { get; set; }
        public string Native { get; set; }
        public string CurrProject { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string JobPartTime { get; set; }
        public string Email { get; set; }
        public string QQ { get; set; }
        public string WeiXin { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> HeadPhotoPic { get; set; }
        public Nullable<int> FingerprintLeftPic { get; set; }
        public Nullable<int> FingerprintRightPic { get; set; }
        public string SkillItem { get; set; }
        public Nullable<int> PicFileId { get; set; }
    }
}
