//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProduct
    {
        public string ProductID { get; set; }
        public int Version { get; set; }
        public string ProductName { get; set; }
        public string ProductSpec { get; set; }
        public Nullable<decimal> ProductQuantity { get; set; }
        public string ProductUnit { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> StateCode { get; set; }
        public string ResFiles { get; set; }
        public string CurrProject { get; set; }
        public string Space { get; set; }
        public string JobPartTime { get; set; }
        public string SkillItem { get; set; }
        public Nullable<int> ProductPic { get; set; }
    }
}
